spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url : jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: NEVER
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: salestracker
server :
     port : 8090
     
